version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    # Ignore RC versions of golang - commented out due to invalid syntax.
    # Docker ignore conditions don't support glob patterns in versions.
    # See: https://github.com/dependabot/dependabot-core/issues/8677
    # ignore:
    #   - dependency-name: golang
    #     versions: ["*rc*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
